export const languageNames = {
    af: "Africâner",
    bg: "Búlgaro",
    ca: "Catalão",
    cs: "Tcheco",
    cy: "Galês",
    da: "Dinamarquês",
    de: "Alemão",
    "de-DE": "Alemão (Alemanha)",
    el: "Grego",
    en: "Inglês",
    "en-AU": "Inglês (Austrália)",
    "en-CA": "Inglês (Canadá)",
    "en-GB": "Inglês (Reino Unido)",
    "en-GB-oxendict": "Inglês (Reino Unido - Oxford)",
    "en-US": "Inglês (Estados Unidos)",
    es: "Espanhol",
    "es-419": "Espanhol (América Latina)",
    "es-AR": "Espanhol (Argentina)",
    "es-ES": "Espanhol (Espanha)",
    "es-MX": "Espanhol (México)",
    "es-US": "Espanhol (Estados Unidos)",
    et: "Estoniano",
    fa: "Persa",
    fo: "Feroês",
    fr: "Francês",
    "fr-FR": "Francês (França)",
    he: "Hebraico",
    hi: "Hindi",
    hr: "Croata",
    hu: "Húngaro",
    hy: "Armênio",
    id: "Indonésio",
    it: "Italiano",
    "it-IT": "Italiano (Itália)",
    ko: "Coreano",
    lt: "Lituano",
    lv: "Letão",
    nb: "Norueguês Bokmål",
    nl: "Holandês",
    pl: "Polonês",
    pt: "Português",
    "pt-BR": "Português (Brasil)",
    "pt-PT": "Português (Portugal)",
    ro: "Romeno",
    ru: "Russo",
    sh: "Sérvio (Latino)",
    sk: "Eslovaco",
    sl: "Esloveno",
    sq: "Albanês",
    sr: "Sérvio (Cirílico)",
    sv: "Sueco",
    ta: "Tâmil",
    tg: "Tajique",
    tr: "Turco",
    uk: "Ucraniano",
    vi: "Vietnamita",
}
